package modelo;
// Generated 05-feb-2019 8:13:07 by Hibernate Tools 4.3.1



/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private Integer id;
     private Restaurante restaurante;
     private String nombre;
     private String descripcion;
     private double precio;
     private String foto;
     private String video;

    public Plato() {
    }

    public Plato(Restaurante restaurante, String nombre, String descripcion, double precio, String foto, String video) {
       this.restaurante = restaurante;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.foto = foto;
       this.video = video;
    }

    public Plato(int id, Restaurante restaurante , String nombre) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.restaurante = restaurante;
       this.id = id;
    }
    public Plato(int id, Restaurante restaurante , String nombre, String descripcion, double precio,String foto, String video) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.restaurante = restaurante;
       this.id = id;
       this.foto = foto;
       this.video = video;
    }

    public Plato(Restaurante user, String nombre, String descripcion, double precio) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.restaurante = user;
       //this.id = id;
       
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Restaurante getRestaurante() {
        return this.restaurante;
    }
    
    public void setRestaurante(Restaurante restaurante) {
        this.restaurante = restaurante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }




}


