package modelo;
// Generated 05-feb-2019 8:13:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurante generated by hbm2java
 */
public class Restaurante  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String tipoComida;
     private String direccion;
     private double valoracion;
     private double pedidoMinimo;
     private String horaApertura;
     private String horaCierre;
     private boolean abierto;
     private Set propietarios = new HashSet(0);
     private Set platos = new HashSet(0);

    public Restaurante() {
    }

	
    public Restaurante(String nombre, String tipoComida, String direccion, double valoracion, double pedidoMinimo, String horaApertura, String horaCierre, boolean abierto) {
        this.nombre = nombre;
        this.tipoComida = tipoComida;
        this.direccion = direccion;
        this.valoracion = valoracion;
        this.pedidoMinimo = pedidoMinimo;
        this.horaApertura = horaApertura;
        this.horaCierre = horaCierre;
        this.abierto = abierto;
    }
    public Restaurante(String nombre, String tipoComida, String direccion, double valoracion, double pedidoMinimo, String horaApertura, String horaCierre, boolean abierto, Set propietarios, Set platos) {
       this.nombre = nombre;
       this.tipoComida = tipoComida;
       this.direccion = direccion;
       this.valoracion = valoracion;
       this.pedidoMinimo = pedidoMinimo;
       this.horaApertura = horaApertura;
       this.horaCierre = horaCierre;
       this.abierto = abierto;
       this.propietarios = propietarios;
       this.platos = platos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoComida() {
        return this.tipoComida;
    }
    
    public void setTipoComida(String tipoComida) {
        this.tipoComida = tipoComida;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public double getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(double valoracion) {
        this.valoracion = valoracion;
    }
    public double getPedidoMinimo() {
        return this.pedidoMinimo;
    }
    
    public void setPedidoMinimo(double pedidoMinimo) {
        this.pedidoMinimo = pedidoMinimo;
    }
    public String getHoraApertura() {
        return this.horaApertura;
    }
    
    public void setHoraApertura(String horaApertura) {
        this.horaApertura = horaApertura;
    }
    public String getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(String horaCierre) {
        this.horaCierre = horaCierre;
    }
    public boolean isAbierto() {
        return this.abierto;
    }
    
    public void setAbierto(boolean abierto) {
        this.abierto = abierto;
    }
    public Set getPropietarios() {
        return this.propietarios;
    }
    
    public void setPropietarios(Set propietarios) {
        this.propietarios = propietarios;
    }
    public Set getPlatos() {
        return this.platos;
    }
    
    public void setPlatos(Set platos) {
        this.platos = platos;
    }




}


